### ISSUE TITLE
requests module version requirement too strict

### ISSUE THREAD

**Issue by martinruefenacht** [iqm-finland/iqm-client#83]
There is currently a conflict between the LRZ requests version usage (2.28.1) and the IQM client requests usage (2.26.0).

I found that version being specified in [setup.cfg](https://github.com/iqm-finland/iqm-client/blob/6a2ea0885af90fbd7fe244fb798c66477a985f4c/setup.cfg).

Is it possible for a looser constraint? Because pip currently doesn't like this.

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
iqm-client 12.2 requires requests==2.26.0, but you have requests 2.28.2 which is incompatible.`

I didn't test this in a clean environment, but a small version bump or >2.26.0 should be fine?

**Comment by freetonik** [comment]
@martinruefenacht hi, the dependency is now relaxed, but, of course, this would affect the latest version of IQM Client only. It is not necessarily compatible with older versions of IQM Server.
